### ISSUE TITLE
Screen Rotation

### ISSUE THREAD

**Issue by kev7040** [jcaruso001/On-The-Go-Now#1]
The Mobile App will not rotate on my Samsung Galaxy Tab.
Running Android Verison 4.4.2

**Comment by jcaruso001** [comment]
I set it to not rotate and have a fixed orientation. Do you want a fixed orientation and it just needs to be the other way or do you not want it fixed at all?

**Comment by jcaruso001** [comment]
As per our conversation we want the screen to rotate and preserve data.

**Comment by jcaruso001** [comment]
Took the override orientation out, test data is kept when orientation is changed.

**Comment by kev7040** [comment]
Done
