### ISSUE TITLE
Users not tied to Company Account

### ISSUE THREAD

**Issue by kev7040** [jcaruso001/On-The-Go-Now#15]
In the Luke Landscaping account - once added the user Barbara - later deleted her and then went to re-add her- get the message that the user already exists in the  On The Go Now domain.

**Comment by dirving2013** [comment]
Can't seem to replicate, can you verify?

**Comment by dirving2013** [comment]
Nevermind, this should be fixed as well

**Comment by kev7040** [comment]
Verified
