### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by kev7040** [jcaruso001/On-The-Go-Now#18]
The App crashes after login info is entered.

It takes a long minute before the all changes to refreshing user data and so on..

A crash report is generated - you should see it under the Beta testers section.

**Comment by jcaruso001** [comment]
I think there were some inconsistency in the API return when there were no values to return. The change was on the website side. Verify it is now working.

**Comment by kev7040** [comment]
All good. Thank You

**Comment by kev7040** [comment]
Thank you jumping on this right away. It is working good now!


Have a good Day!

**Comment by kev7040** [comment]
Hi Jason,

Just wondering, can the administrator of the portal account log into the app or do they have to create a regular account?

Under Luke Landscape Contractors the admin account is under dan@lukelandscaping.com but I also created him a regular account with the same 
e-mail address. - Just wondering - with the how to go about this for future.

Thank You,

Kevin
