### ISSUE TITLE
Spacing on Reports Pages

### ISSUE THREAD

**Issue by kev7040** [jcaruso001/On-The-Go-Now#4]
Can we increase the spacing between the Menu choices on each of the Clock In/Out and Equipment etc pages. Have it take up more of the free Realestate?  And make the Drop down menu's text bigger.

**Comment by jcaruso001** [comment]
All devices are different so if we are targeting only a specific size we can scale the screens for that. I cannot remember if you said we were or not. 

Otherwise if we make it sized for a 10 in tablet it will look bad on a 7 in.

**Comment by kev7040** [comment]
Ok - Sounds good.

**Comment by jcaruso001** [comment]
I didn't really get any help, is it a 10 or 7 in. Are we targeting one of those only or all devices?

**Comment by jcaruso001** [comment]
As per our conversation I will do what I can to compair the differences between a phone and tablet layout to try and use up the available white space on all the screens.

**Comment by jcaruso001** [comment]
I modified the spacing on all the pages... First I made most of the objects on the screen wider but I also centered the whole thing. So now the fields show be on the center of each page unless your on a smaller device that you must scroll up and down on.

**Comment by kev7040** [comment]
Done
