### ISSUE TITLE
Travel Time

### ISSUE THREAD

**Issue by kev7040** [jcaruso001/On-The-Go-Now#5]
On the Clock In and Out pages - Need to bring the Travel Time clock over in the middle, maybe replace it with button that says Travel Time?  

Also when you tap on the Travel time - can we instead of having the show all hours in a clock - Can we have Minutes portion show 1 minute(s) and then scroll up higher and the Hours section show 0 at first? 

Can we remove the AM/PM section?

**Comment by jcaruso001** [comment]
This issue has been broken up into two issues... #7 and #8
